### PR TITLE
working version of fast TPC transformation with irregular splines and flat buffer

### PR DESCRIPTION
**Pull request by sgorbuno**
Hi Jens, 

I think I managed to squash my commits into one.
The README.md I'll write a bit later.

Sergey.

### CODE REVIEW

**Comment by wiechula** [comment]
Hi Sergey,
very good. Do you have a macro which shows how to use the code you could commit in addition?
Jens

**Comment by sgorbuno** [comment]
There are some benchmark macros in macro/ directory and TPCFastTransformQA class where the transformation is created and benchmarked. 
We will start to use it soon with David. There will be more code and macros then.
This is just a first working version to start with.

**Comment by sgorbuno** [comment]
Hi Jens,
Currently, to create a transformation object, one should call TPCFastTransformManager::create() somewhere from AliRoot simulation/reconstruction. I'll write a macro for this, but I don't have it yet.
Sergey.

**Comment by davidrohr** [comment]
Hi Sergey,
a few comments:
- Do we need the FlatObject.cxx if the object is header-only?
- In order to actually build and run this, we need a PR to AliRoot and O2 to build the libraries. Do you already have such a branch available? Also, the TPCFastTransformation/CMakeList.txt seems to be only a placeholder right now, as it doesn't have SRCS defined.
- We'll need some more stuff in AliRoot to validate this: An component, or a modified AliHLTTPCTransformationComponent that uses the new transformation instead of the old one.
A macro to create the transformation map in the new format, and a way to do it on the fly in the transformation component.
- I had a look at the FlatObject.h and it looks reasonable. Do you have an example macro how to move the object to a different memory space, i.e. GPU?

**Comment by sgorbuno** [comment]
Hi David, 
- The FlatObject.cxx can be removed.

- I compiled it only with AilRoot, not with O2. The AliRoot code is in a pull request : https://github.com/alisw/AliRoot/pull/752  
To add the transformation code to AliRoot compilation one has to uncomment there 2 lines  in HLT/TPCLib/CMakeList.txt. 
I commented it out in order to not to break the AliRoot compilation. Since the transformation code is not yet in the AliTPCCommon library. 
SRCS are set only for AliRoot compilation somewhere later in the CMakeLists.txt. 

- creating the object on-the-fly is easy.  In my pull request there is a code in AliHLTTPCTransformationComponent (it is commented out) which creates new transformation and runs its qa. I can make a flag to let run HLT with the new transformation. But first the transformation  should be present in the AliTPCCommon library. 
The macro is missing at the moment. I'll create it as soon as i'll manage to  rebuild my AliRoot.. 

- no, this macro is also missing. There is a description how to do it in FlatObject.h.

**Comment by davidrohr** [comment]
Hi Sergey, thanks, I missed the AliRoot PR, sorry.
I think we should clean up the CMakeList in AliTPCCommon, and unify the build for AliRoot / O2, let's discuss that later. I can handle the O2 part, if you don't have that set up right now. Also, we should check that we do not break the ROOT6 release validation, where we had some issues in AliTPCCommon with include files. I'll check that later.

**Comment by davidrohr** [comment]
Hi @sgorbuno : I have updated your PR, moved the flat object to a Common directory, removed obsolete includes and libraries, and cleaned up the CMake.
Could you have a look at https://github.com/davidrohr/AliTPCCommon/tree/master
It contains another commit to make most of AliTPCCommon and youf FastTransform part compile with ROOT5 (I am still waiting for a fix from Ole, before we can make the TRD part compile with ROOT5.)
If you are fine with the changes, I'd push my branch to the AliTPCCommon master (I cannot rewrite your PR).

**Comment by sgorbuno** [comment]
Hi David, 
Thanks!  Fine with me, you can push. 
Sergey.

**Comment by davidrohr** [comment]
Adjusted version of this PR has been merged manually. Closing this.

**Pull request closed without merging**
