### PR TITLE
Bugfixes and new implementation for TPC space charge

### PR DESCRIPTION
**Pull request by ehellbar**
* Distortions -- irregular interpolation fix with kdtree

Add kdtree to irregular interpolator

Fix correction calculation of RPhi

Distortions modification as Ernst suggest

Integration on exact function

* Add correction with side information

* Remove comments and updates on phi r distortion

### CODE REVIEW

**Comment by ehellbar** [comment]
Hello David,

here we fix some bugs in the signs and calculation of the space-charge distortions and add some new implementations for irregular grid lookup tables and integration along the drift lines.

It would be nice to get a new tag with these changes. Are there other changes which will be tagged soon?

Cheers,
Ernst

**Comment by davidrohr** [comment]
Hi @ehellbar, this does not compile for me in AliRoot (see below):

/home/qon/alice/sw/SOURCES/AliRoot/0_O2/0/TPC/TPCbase/AliTPCSpaceCharge3DDriftLine.cxx: In member function ‘void AliTPCSpaceCharge3DDriftLine::InitSpaceCharge3DPoissonIntegralDz(Int_t, Int_t, Int_t, Int_t, Double_t, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TFormula*, TFormula*, TFormula*)’:
/home/qon/alice/sw/SOURCES/AliRoot/0_O2/0/TPC/TPCbase/AliTPCSpaceCharge3DDriftLine.cxx:149:67: error: no matching function for call to ‘AliTPCSpaceCharge3DCalc::InitSpaceCharge3DPoissonIntegralDz(Int_t&, Int_t&, Int_t&, Int_t&, Double_t&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TMatrixD**&, TFormula*&, TFormula*&, TFormula*&)’
     intErDzTestFunction, intEPhiRDzTestFunction, intDzTestFunction);
                                                                   ^
In file included from /home/qon/alice/sw/SOURCES/AliRoot/0_O2/0/TPC/TPCbase/AliTPCSpaceCharge3DDriftLine.h:26,
                 from /home/qon/alice/sw/SOURCES/AliRoot/0_O2/0/TPC/TPCbase/AliTPCSpaceCharge3DDriftLine.cxx:36:
/home/qon/alice/sw/gentoo2_x86-64/AliGPU/master-1/sources/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.h:35:8: note: candidate: ‘void AliTPCSpaceCharge3DCalc::InitSpaceCharge3DPoissonIntegralDz(Int_t, Int_t, Int_t, Int_t, Double_t)’
   void InitSpaceCharge3DPoissonIntegralDz(Int_t nRRow, Int_t nZColumn, Int_t phiSlice, Int_t maxIteration,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/qon/alice/sw/gentoo2_x86-64/AliGPU/master-1/sources/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.h:35:8: note:   candidate expects 5 arguments, 26 provided
/home/qon/alice/sw/gentoo2_x86-64/AliGPU/master-1/sources/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.h:37:8: note: candidate: ‘void AliTPCSpaceCharge3DCalc::InitSpaceCharge3DPoissonIntegralDz(Int_t, Int_t, Int_t, Int_t, Double_t, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TMatrixD**, TFormula*, TFormula*, TFormula*, TFormula*)’
   void InitSpaceCharge3DPoissonIntegralDz(
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/qon/alice/sw/gentoo2_x86-64/AliGPU/master-1/sources/TPCSpaceChargeBase/AliTPCSpaceCharge3DCalc.h:37:8: note:   candidate expects 27 arguments, 26 provided

**Comment by davidrohr** [comment]
Hi Ernst,
we have a JIRA ticket (https://alice.its.cern.ch/jira/browse/ALIROOT-8188) open to merge a couple of changes, and I will integrate yours once AliRoot compilation is fixed (hopefully be end of next week, as Dario is quite busy at the moment).

**Comment by ehellbar** [comment]
Hello David,
you are right. @rsadikin modified a function definition in AliTPCCommon which is used in AliRoot, so in order for this version to work we would need a PR with the corresponding changes in AliRoot. Is there a way to simultaneously make the changes? Atm, I cannot think of one, so we need to do it step by step?

**Comment by davidrohr** [comment]
No, there is no good way, only the admins can merge both repos simulataneously but that is always a bit complicated. But Dario anyway wants to move everything into O2 now.

**Comment by ehellbar** [comment]
Hello @davidrohr and Rifki,
I restored the old functionality which is compiling with aliroot in addition to the new modifications. This version works with the current aliroot master and should also work after pushing the changes in aliroot.

**Comment by davidrohr** [comment]
works now

**Pull request merged**
