### PR TITLE
feature trdtracking

### PR DESCRIPTION
**Pull request by martenole**
Move code from $AliRoot/HLT/TRD/tracking to $AliTPCCommon/TPCCAGPUTracking/TRDTracking including latest commits using template classes

### CODE REVIEW

**Comment by wiechula** [comment]
These are quite some commits, do we need the full history, or can a part, or all be squased?
In sense it is an initial commit.

**Comment by davidrohr** [comment]
we decided to move the historyfrom aliroot. we did the samefor the tpctracking, so this should be ok. afterwards we will remove the codefrom aliroot.
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by wiechula** [comment]
ok fine

**Comment by davidrohr** [comment]
Cool, nicely moved the history and pretty clean. I am merging this right now (doesn't change anything yet), will fix the build system for the TRD with templates and the HLT track params soon.

**Pull request merged**
