### PR TITLE
Add VertexerTraits in AliGPUReconstruction

### PR DESCRIPTION
**Pull request by mconcas**
This PR will add the possibility to get the VertexerTraits from the `AliGPUReconstruction` interface.

### CODE REVIEW

**Comment by davidrohr** [comment]
I am wondering, there is a class VertexerTraits and VertexerTraitsCPU, why isn't the CPU version of the class used?

**Comment by mconcas** [comment]
> I am wondering, there is a class VertexerTraits and VertexerTraitsCPU, why isn't the CPU version of the class used?

The VertexerTraitsCPU will be dropped next PRs iteration.
As we said on latest meeting, the CPU version now is VertexerTraits, and the VertexerTraitsGPU will override some methods using GPU.
Hence, we reduce the number of interfaces, making this even more usable.

**Comment by davidrohr** [comment]
OK, I'll rebase and merge it manually.

Btw, testing it I saw several warnings in the ITS Tracking code you might want to fix, and you could remove the gsl/gsl header from ROFrame.h, as it is not used.

/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx: In member function ‘virtual void o2::ITS::VertexerTraits::initialise(o2::ITS::ROframe*)’:
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:61:41: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
       for (auto iCluster{ 0 }; iCluster < clustersNum; ++iCluster) {
                                ~~~~~~~~~^~~~~~~~~~~~~
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:72:40: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
       for (int iCluster{ 0 }; iCluster < clustersNum; ++iCluster) {
                               ~~~~~~~~~^~~~~~~~~~~~~
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx: In member function ‘virtual void o2::ITS::VertexerTraits::computeTracklets(bool)’:
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:140:34: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::pair<int, int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
       for (int iRow0{ 0 }; iRow0 < clusters0.size(); ++iRow0) {
                            ~~~~~~^~~~~~~~~~~~~~~~~~
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:172:40: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::pair<int, int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
             for (int iRow2{ 0 }; iRow2 < clusters2.size(); ++iRow2) {
                                  ~~~~~~^~~~~~~~~~~~~~~~~~
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:152:19: warning: unused variable ‘ZProjectionInner’ [-Wunused-variable]
             float ZProjectionInner{ mClusters[0][iCluster0].zCoordinate +

In file included from /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/ClusterLines.cxx:12:
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/include/ITStracking/ClusterLines.h: In constructor ‘o2::ITS::Line::Line()’:
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/include/ITStracking/ClusterLines.h:32:24: warning: ‘o2::ITS::Line::weightMatrix’ will be initialized after [-Wreorder]
   std::array<float, 6> weightMatrix;
                        ^~~~~~~~~~~~
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/include/ITStracking/ClusterLines.h:31:37: warning:   ‘std::array<float, 3> o2::ITS::Line::cosinesDirector’ [-Wreorder]
   std::array<float, 3> originPoint, cosinesDirector;
                                     ^~~~~~~~~~~~~~~
/home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/ClusterLines.cxx:19:1: warning:   when initialized here [-Wreorder]
 Line::Line() : originPoint{}, weightMatrix{ std::array<float, 6>{ 1., 0., 0., 1., 0., 1. } }, cosinesDirector{}

**Comment by mconcas** [comment]
> OK, I'll rebase and merge it manually.
> 
> Btw, testing it I saw several warnings in the ITS Tracking code you might want to fix, and you could remove the gsl/gsl header from ROFrame.h, as it is not used.
> 
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx: In member function ‘virtual void o2::ITS::VertexerTraits::initialise(o2::ITS::ROframe*)’:
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:61:41: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
> for (auto iCluster{ 0 }; iCluster < clustersNum; ++iCluster) {
> ~~~~~~~~~^~~~~~~~~~~~~
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:72:40: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
> for (int iCluster{ 0 }; iCluster < clustersNum; ++iCluster) {
> ~~~~~~~~~^~~~~~~~~~~~~
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx: In member function ‘virtual void o2::ITS::VertexerTraits::computeTracklets(bool)’:
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:140:34: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::pair<int, int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
> for (int iRow0{ 0 }; iRow0 < clusters0.size(); ++iRow0) {
> ~~~~~~^~~~~~~~~~~~~~~~~~
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:172:40: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::pair<int, int> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
> for (int iRow2{ 0 }; iRow2 < clusters2.size(); ++iRow2) {
> ~~~~~~^~~~~~~~~~~~~~~~~~
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/VertexerTraits.cxx:152:19: warning: unused variable ‘ZProjectionInner’ [-Wunused-variable]
> float ZProjectionInner{ mClusters[0][iCluster0].zCoordinate +
> 
> In file included from /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/ClusterLines.cxx:12:
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/include/ITStracking/ClusterLines.h: In constructor ‘o2::ITS::Line::Line()’:
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/include/ITStracking/ClusterLines.h:32:24: warning: ‘o2::ITS::Line::weightMatrix’ will be initialized after [-Wreorder]
> std::array<float, 6> weightMatrix;
> ^~~~~~~~~~~~
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/include/ITStracking/ClusterLines.h:31:37: warning: ‘std::array<float, 3> o2::ITS::Line::cosinesDirector’ [-Wreorder]
> std::array<float, 3> originPoint, cosinesDirector;
> ^~~~~~~~~~~~~~~
> /home/qon/alice/O2//Detectors/ITSMFT/ITS/tracking/src/ClusterLines.cxx:19:1: warning: when initialized here [-Wreorder]
> Line::Line() : originPoint{}, weightMatrix{ std::array<float, 6>{ 1., 0., 0., 1., 0., 1. } }, cosinesDirector{}

Thanks for pointing them out. I'm fixing next PR on O2.
For curiosity, what compiler are you using?

**Comment by davidrohr** [comment]
I usually compile with gcc 8, but I also use clang to test for warnings. These actually showed up using hipcc, which is basically clang 8.

**Comment by davidrohr** [comment]
Rebased version is in AliTPCCommon master and works standalone and with O2. Will become part of next tag (but not the 2.3.3 tag that is still stuck waiting for an AliRoot release...)

**Pull request closed without merging**
